"""
Pack the audio files in `sounds/` into the app, so they ship inside it and nobody can swap them.

    python tools/pack_sounds.py

Writes shield_sounds_data.py next to shield.py. Run it whenever the files in `sounds/` change, then build as usual. Because
shield_sound.py imports that module, PyInstaller picks it up on its own: no --add-data needed. (Audio is stored compressed,
then base64, so expect the .py to be roughly as large as the audio.) Keep clips short.
"""
import base64
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXTS = {".wav", ".mp3", ".ogg", ".flac", ".m4a", ".aac", ".opus"}


def main():
    files = sorted(f for f in (ROOT / "sounds").glob("*") if f.suffix.lower() in EXTS)
    if not files:
        print("No audio files found in sounds/. Nothing packed.")
        return 1
    out = ['"""Generated by tools/pack_sounds.py. Do not edit: run the tool again instead."""', "FILES = {"]
    total = 0
    for f in files:
        raw = f.read_bytes()
        total += len(raw)
        blob = base64.b64encode(zlib.compress(raw, 9)).decode("ascii")
        out.append(f"    {f.name.lower()!r}: (")
        out += [f"        {blob[i:i + 100]!r}" for i in range(0, len(blob), 100)]
        out.append("    ),")
        print(f"packed {f.name} ({len(raw) / 1024:.1f} KB)")
    out.append("}")
    (ROOT / "shield_sounds_data.py").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote shield_sounds_data.py with {len(files)} sound(s), {total / 1024:.0f} KB of audio.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
